# SPDX-License-Identifier: GPL-2.0-only

function(kobox_check_production_targets)
	foreach(_target IN LISTS ARGN)
		get_target_property(_sources ${_target} SOURCES)
		foreach(_source IN LISTS _sources)
			if(_source MATCHES "(^|/)(tests|test|fixture)/|_test\\.|_fixture\\.|qemu|qtest")
				message(FATAL_ERROR "Test source in production target ${_target}: ${_source}")
			endif()
		endforeach()
		get_target_property(_links ${_target} LINK_LIBRARIES)
		foreach(_link IN LISTS _links)
			if(_link STREQUAL "kobox2::protocol")
				continue()
			endif()
			if(TARGET "${_link}")
				get_target_property(_imported "${_link}" IMPORTED)
				if(NOT _imported AND NOT _link IN_LIST ARGN)
					message(FATAL_ERROR "Non-production dependency of ${_target}: ${_link}")
				endif()
			endif()
		endforeach()
	endforeach()
endfunction()
