/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef KOBOX_PROVIDER_LINUX_STATIC_CALL_H
#define KOBOX_PROVIDER_LINUX_STATIC_CALL_H

#ifdef KOBOX_BOOT_RUNTIME
/* The full boot core includes the upstream static-call implementation. */
#include_next <linux/static_call.h>
#else

#ifdef CONFIG_HAVE_STATIC_CALL_INLINE
#define KOBOX_RESTORE_HAVE_STATIC_CALL_INLINE
#undef CONFIG_HAVE_STATIC_CALL_INLINE
#endif
#ifdef CONFIG_HAVE_STATIC_CALL
#define KOBOX_RESTORE_HAVE_STATIC_CALL
#undef CONFIG_HAVE_STATIC_CALL
#endif

#include_next <linux/static_call.h>

#ifndef EXPORT_STATIC_CALL_TRAMP
#define EXPORT_STATIC_CALL_TRAMP(name) \
	EXPORT_SYMBOL(STATIC_CALL_KEY(name))
#define EXPORT_STATIC_CALL_TRAMP_GPL(name) \
	EXPORT_SYMBOL_GPL(STATIC_CALL_KEY(name))
#endif

#ifdef KOBOX_RESTORE_HAVE_STATIC_CALL
#define CONFIG_HAVE_STATIC_CALL 1
#undef KOBOX_RESTORE_HAVE_STATIC_CALL
#endif
#ifdef KOBOX_RESTORE_HAVE_STATIC_CALL_INLINE
#define CONFIG_HAVE_STATIC_CALL_INLINE 1
#undef KOBOX_RESTORE_HAVE_STATIC_CALL_INLINE
#endif

#endif /* KOBOX_BOOT_RUNTIME */

#endif /* KOBOX_PROVIDER_LINUX_STATIC_CALL_H */
